FROM phusion/passenger-ruby22
MAINTAINER Victor Lellis <vmlellis@gmail.com>

# Run Bundle in a cache efficient way
WORKDIR /tmp
ADD Gemfile* /tmp/
RUN bundle install

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Start Nginx / Passenger
RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default

# Add the nginx info
ADD webapp.conf /etc/nginx/sites-enabled/webapp.conf

ENV APP_HOME /home/app

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
