# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25ceab4047ba73634cb02dfdbfa1756f696a49d1ac9d97069783e5e2a9d3676195e821db022eec1297b9e3950508690743646161e7b3d1ed40906c9aa79cdb74

test:
  secret_key_base: 355dd024e5aad42b90df94a37830e4191d64a160ea0b8462ba7242254bfcd4a2a69bc3a4151fd581834253a0c090c58dbc9683f840cd8baadd29812cdf324b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
